name: Allure Report

on:
  push:
    branches:
      - cliff/dev/action_bugfix

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      
      - name: Build and run tests with Maven
        run: mvn verify
      
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history